### ISSUE TITLE
Github release still shows only 1.0.2

### ISSUE THREAD

**Issue by nakedible-p** [swimos/ratchet#47]
Minor nit – crates has 1.0.3, but github releases only has 1.0.2. If your plan is not to use github releases, it probably should be mentioned somewhere.

**Comment by SirCipher** [comment]
@nakedible-p, we do use them I just forgot to make that release unfortunately. I will have a new one for 1.1 soon

**Comment by SirCipher** [comment]
@nakedible-p now released v1.1.0
