### ISSUE TITLE
Semver breakage with 1.1.0 and ratchet_rs

### ISSUE THREAD

**Issue by nakedible-p** [swimos/ratchet#49]
It seems that if upgrading `ratchet_rs` from 1.0.3 to 1.1.0 and not touching `Cargo.lock`, you will end up with `ratchet_rs` of 1.1.0 and `ratchet_core` of `1.0.3` which will not compile.

And vice versa, if one specifies `ratchet_rs` of `=1.0.3` in `Cargo.toml`, it will pull in `ratchet_core` of `1.1.0` due to semver compatibility, which will not compilre.

Each version of `ratchet_rs` should probably depend on its crate mates with exact versions, but I'm not sure if there's an easy way to fix the already released versions.

**Comment by SirCipher** [comment]
@nakedible-p this was due to a version mismatch in the workspace. I've resolved it and tidied up dependency declaration.
