### ISSUE TITLE
Consider adding `ExtensionProvider` impl for `Option<ExtensionProvider>`

### ISSUE THREAD

**Issue by nakedible-p** [swimos/ratchet#50]
We need to be able to disable compression at runtime, based on a flag. Meaning that even if the client proposes to use deflate, the server will not support that extension. How we solved that outside of Ratchet was simply:

```rust
struct OptionalProvider<T>(Option<T>);

impl<T: ExtensionProvider> ExtensionProvider for OptionalProvider<T> {
    type Extension = T::Extension;
    type Error = T::Error;
    fn apply_headers(&self, headers: &mut hyper::HeaderMap) {
        if let Some(provider) = &self.0 {
            provider.apply_headers(headers);
        }
    }
    fn negotiate_client(&self, headers: &hyper::HeaderMap) -> Result<Option<Self::Extension>, Self::Error> {
        self.0.as_ref().map_or(Ok(None), |provider| provider.negotiate_client(headers))
    }

    fn negotiate_server(&self, headers: &hyper::HeaderMap) -> Result<Option<(Self::Extension, ratchet_ext::HeaderValue)>, Self::Error> {
        self.0.as_ref().map_or(Ok(None), |provider| provider.negotiate_server(headers))
    }
}
```

But Ratchet could implement it directly for `Option<T>`.

Just a suggestion though, might be too obscure.

**Comment by SirCipher** [comment]
@nakedible-p the last release did actually implement it for Option which superseded the NegotiatedExtension system

**Comment by nakedible-p** [comment]
This is unrelated, but two other issues quickly:
- `ratchet_core::server::handshake` takes in `&ExtensionProvider`, but `ratchet_core::server::response_from_headers` takes in `ExtensionProvider`. Doesn't make a difference, but I don't think this is intentional.
- Neither `handshake` nor `response_from_headers` returns the selected subprotocol, forcing the user to either look into the returned header manually, or to use `parse_request_parts` and `build_response_headers` manually.

**Comment by SirCipher** [comment]
@nakedible-p I'll get that fixed in the next release too
